config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :task_logs
  root to: 'tasks#index'
  resources :tasks
  devise_for :users, path_prefix: 'oauth'
  resources :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
# frozen_string_literal: true

class Task < ApplicationRecord
  belongs_to :user
  enum status: %i[em_andamento finalizado]

  validates :title, :description, presence: true
  validates_associated :user

  has_many :task_logs
end

app/models/task_log.rb
# frozen_string_literal: true

class TaskLog < ApplicationRecord
  belongs_to :task
  belongs_to :user

  validates :description, presence: true
  validates_associated :user
  validates_associated :task

  after_create :close_task

  protected

  def close_task
    return true unless finished?
    task.update_attribute(:status, 'finalizado')
  end
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  enum kind_of: %i[administrador operador]

  scope :administrators, -> { where(kind_of: 'administrador') }
  scope :operators, -> { where(kind_of: 'operador') }

  validates :name, presence: true
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  layout :layout_by_resource

  protected

  def layout_by_resource
    if devise_controller?
      'devise'
    else
      'application'
    end
  end

  def redirect_unless_operator
    redirect_to root_path if current_user.nil? || !current_user.administrador?
  end
end

app/controllers/dashboard_controller.rb
# frozen_string_literal: true

class DashboardController < ApplicationController
  before_action :authenticate_user!
  def index; end
end

app/controllers/task_logs_controller.rb
# frozen_string_literal: true

class TaskLogsController < ApplicationController
  before_action :authenticate_user!
  # GET /task_logs.json
  def index
    respond_to do |format|
      format.json { render json: TaskLogDatatable.new(view_context) }
    end
  end

  # POST /task_logs
  # POST /task_logs.json
  def create
    @task_log = TaskLog.new(task_log_params)
    @task_log.user_id = current_user.id

    respond_to do |format|
      if @task_log.save
        format.html { redirect_to edit_task_path(@task_log.task_id), notice: I18n.t(:success_operation) }
        format.json { render :show, status: :created, location: @task_log }
      else
        format.html { render edit_task_path(@task_log.task_id) }
        format.json { render json: @task_log.errors, status: :unprocessable_entity }
      end
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_task_log
    @task_log = TaskLog.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def task_log_params
    params.require(:task_log).permit(:task_id, :description, :finished)
  end
end

app/controllers/tasks_controller.rb
# frozen_string_literal: true

class TasksController < ApplicationController
  before_action :authenticate_user!
  before_action :set_task, only: %i[edit update destroy]
  before_action :redirect_unless_operator, except: %i[index new create edit]

  # GET /tasks
  # GET /tasks.json
  def index
    respond_to do |format|
      format.html
      format.json { render json: TaskDatatable.new(view_context) }
    end
  end

  # GET /tasks/new
  def new
    @task = Task.new
  end

  # GET /tasks/1/edit
  def edit; end

  # POST /tasks
  # POST /tasks.json
  def create
    @task = Task.new(task_params)
    @task.user_id = current_user.id unless current_user.administrador?

    respond_to do |format|
      if @task.save
        format.html { redirect_to edit_task_path(@task), notice: I18n.t(:success_operation) }
        format.json { render :show, status: :created, location: @task }
      else
        format.html { render :new }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tasks/1
  # PATCH/PUT /tasks/1.json
  def update
    respond_to do |format|
      if @task.update(task_params)
        format.html { redirect_to edit_task_path(@task), notice: I18n.t(:success_operation) }
        format.json { render :show, status: :ok, location: @task }
      else
        format.html { render :edit }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tasks/1
  # DELETE /tasks/1.json
  def destroy
    @task.destroy
    respond_to do |format|
      format.html { redirect_to tasks_url, notice: I18n.t(:success_operation) }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_task
    @task = Task.where(id: params[:id])
    @task = @task.where(user_id: current_user.id) unless current_user.administrador?
    @task = @task.first
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def task_params
    params.require(:task).permit(:user_id, :title, :description, :scheduled_to, :status)
  end
end

app/controllers/users_controller.rb
# frozen_string_literal: true

class UsersController < ApplicationController
  before_action :authenticate_user!
  before_action :redirect_unless_operator
  before_action :set_user, only: %i[edit update destroy]

  # GET /users
  # GET /users.json
  def index
    respond_to do |format|
      format.html
      format.json { render json: UserDatatable.new(view_context) }
    end
  end

  # GET /users/1
  # GET /users/1.json
  def show; end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit; end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to users_url, notice: I18n.t(:success_operation) }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        bypass_sign_in(@user) if current_user.nil? || @user.id == current_user.id
        format.html { redirect_to users_url, notice: I18n.t(:success_operation) }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: I18n.t(:success_operation) }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_user
    @user = User.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def user_params
    params.require(:user).permit(:email, :password, :password_confirmation, :current_password,
                                 :skip_password_validation, :name, :kind_of)
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/helpers/users_helper.rb
# frozen_string_literal: true

module UsersHelper
  def users_options_by_role
    users = User.order('name DESC')
    users = users.where(id: current_user.id) unless current_user.administrador?
    users.collect { |u| [u.name, u.id] }
  end
end

app/views/dashboard/index.html.erb
<h1>Em desenvolvimento...</h1>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

<head>
  <title><%=t(:application_name)%></title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <!-- Google Maps API Key - Use your own API key to enable the map feature. More information on the Google Maps API can be found at https://developers.google.com/maps/
    <script type="text/javascript" src="https://maps.googleapis.com/maps/api/js?key=AIzaSyCRngKslUGJTlibkQ3FkfTxj3Xss1UlZDA&sensor=false"></script> -->

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  </head>

  <body>
    <div class="navbar navbar-expand-lg fixed-top navbar-dark bg-primary">
      <div class="container">
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive"
        aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarResponsive">
        <ul class="navbar-nav">
          <li class="nav-item">
            <%= link_to image_tag('logo_header.png', height: 40), root_path, class: 'nav-link', style: 'padding:0' %>
          </li>
          <li class="nav-item">
            <%= link_to 'Dashboard de Tarefas', root_path, class: 'nav-link' %>
          </li>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" data-toggle="dropdown" href="#" id="themes">Tarefas
              <span class="caret"></span>
            </a>
            <div class="dropdown-menu" aria-labelledby="themes">
              <%= link_to 'Lista de Tarefas', tasks_path, class: 'dropdown-item' %>
              <%= link_to 'Criar Tarefa', new_task_path, class: 'dropdown-item' %>
            </div>
          </li>
          <% if current_user.administrador? %>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" data-toggle="dropdown" href="#" id="download">Controle de Acessos
              <span class="caret"></span>
            </a>
            <div class="dropdown-menu" aria-labelledby="themes">
              <%= link_to 'Lista de Usuários', users_path, class: 'dropdown-item' %>
              <%= link_to 'Criar Usuário', new_user_path, class: 'dropdown-item' %>
            </div>
          </li>
          <% end %>
          <li class="nav-item">
            <%= link_to 'Sair', destroy_user_session_path, method: :delete, class: 'nav-link' %>
          </li>
        </ul>

      </div>
    </div>
  </div>
  <div class="container">
    <% unless notice.blank? %>
    <div class="alert alert-info mb-3">
      <%= notice %>
    </div>
    <% end %>
    <%= yield %>
    <p class="mb-3 text-muted text-center">Construído por
      <a href="http://www.clickmob.com.br/" target="_blank">clickmob.com.br</a>
    </p>
  </div>
</body>

</html>

app/views/layouts/devise.html.erb
<!DOCTYPE html>
<html>

<head>
  <title><%=t(:application_name)%></title>
  <%= stylesheet_link_tag    'devise', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'devise', 'data-turbolinks-track': 'reload' %>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
</head>

<body>
  <div class="container text-center">
    <%= image_tag "logo.jpg", width: 300, class: 'mb-3' %>
    <%= yield %>
    <p class="mb-3 text-muted">Construído por
      <a href="http://www.clickmob.com.br/" target="_blank">clickmob.com.br</a>
    </p>
  </div>
</body>

</html>

app/views/task_logs/_form.html.erb
<hr />
<h5>Adicionar Log de Anotações</h5>
<%= form_with(model: task_log, local: true) do |form| %>
  <%= form.hidden_field :task_id %>
  <% if task_log.errors.any? %>
    <div class="alert alert-danger">
      <h5><%= t('errors_on_save') %></h5>

      <ul>
      <% task_log.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-row">
    <div class="form-group col-md-12">
      <%= form.label :description %>
      <%= form.text_area :description, class: 'form-control' %>
    </div>
  </div>

  <% unless task_log.task.finalizado? %>
  <div class="form-row">
    <div class="form-group col-md-12">
      <%= form.label :finished %>
      <%= form.check_box :finished %>
    </div>
  </div>
  <% end %>

  <div class="actions">
    <div class="btn-group" role="group" aria-label="Ações">
      <%= form.submit 'Adicionar Anotação', class: 'btn btn-sm btn-primary' %>
    </div>
  </div>
<% end %>

app/views/task_logs/_index.html.erb
<hr />
<%= render partial: 'task_logs/task_logs_table', locals: { task_id: @task.id } %>

app/views/task_logs/_task_logs_table.html.erb
<h5>Lista de Anotações</h5>
<table id="task-logs-datatable" data-source="<%= task_logs_path(task_id: task_id, format: :json) %>" class="table mt-3 mb-3">
  <thead>
    <tr>
      <th>Descrição</th>
      <th>Responsável</th>
    </tr>
  </thead>
  <tbody>
  </tbody>
</table>

app/views/tasks/_form.html.erb
<%= form_with(model: @task, url: (@task.new_record? ? tasks_path : task_path(@task)), local: true) do |form| %>
  <% if @task.errors.any? %>
    <div class="alert alert-danger">
      <h5><%= t('errors_on_save') %></h5>

      <ul>
      <% @task.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-row">
    <div class="form-group col-md-4">
      <%= form.label :user_id %>
      <%= form.select :user_id, users_options_by_role, {}, class: 'form-control' %>
    </div>
    <div class="form-group col-md-4">
      <%= form.label :title %>
      <%= form.text_field :title, class: 'form-control' %>
    </div>
    <div class="form-group col-md-4">
      <%= form.label :status %>
      <%= form.select :status, [['Em andamento', 'em_andamento'],['Finalizado', 'finalizado']],{},class: 'form-control' %>
    </div>
  </div>

  <div class="form-row">
    <div class="form-group col-md-12">
      <%= form.label :description %>
      <%= form.text_area :description, class: 'form-control' %>
    </div>
  </div>

  <div class="form-row">
    <div class="form-group col-md-12">
      <%= form.label :scheduled_to %>
      <%= form.datetime_select :scheduled_to, {}, class: 'form-control', style: 'width: auto !important; display: inline' %>
    </div>
  </div>

  <div class="actions mt-3">
    <div class="btn-group" role="group" aria-label="Ações">
      <%= form.submit 'Salvar', class: 'btn btn-sm btn-primary' %>
      <%= link_to 'Voltar para Lista', tasks_path, class: 'btn btn-sm btn-info' %>      
    </div>
  </div>
<% end %>

app/views/tasks/_tasks_table.html.erb
<table id="tasks-datatable" data-source="<%= tasks_path(format: :json) %>" class="table mt-3 mb-3">
  <thead>
    <tr>
      <th>Título</th>
      <th>Responsável</th>
      <th>Status</th>
      <th>Ações</th>
    </tr>
  </thead>
  <tbody>
  </tbody>
</table>

<%= link_to 'Criar Tarefa', new_task_path, class: 'btn btn-sm btn-info mt-3' %>

app/views/tasks/edit.html.erb
<div class="jumbotron">
	<h4 class="mb-3">Editar Tarefa</h4>

	<%= render 'form' %>
	<%= render partial: 'task_logs/form', locals: { task_log: TaskLog.new(task_id: @task.id) } %>
	<%= render partial: 'task_logs/index', locals: { task_id: @task.id } %>
</div>

app/views/tasks/index.html.erb
<div class="jumbotron">
	<h4 class="mb-3">Lista de Tarefas</h4>

	<%= render partial: 'tasks_table' %>
</div>

app/views/tasks/new.html.erb
<div class="jumbotron">
	<h4 class="mb-3">Criar Tarefa</h4>

	<%= render 'form' %>
</div>

app/views/users/_form.html.erb
<%= form_with(model: @user, url: (@user.new_record? ? users_path : user_path(@user)), local: true) do |form| %>
  <% if @user.errors.any? %>
    <div class="alert alert-danger">
      <h5><%= t('errors_on_save') %></h5>

      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-row">
    <div class="form-group col-md-12">
      <%= form.label :name %>
      <%= form.text_field :name, class: 'form-control' %>
    </div>
  </div>

  <div class="form-row">
    <div class="form-group col-md-6">
      <%= form.label :email %>
      <%= form.text_field :email, class: 'form-control' %>
    </div>
    <div class="form-group col-md-6">
      <%= form.label :kind_of %>
      <%= form.select :kind_of, User.kind_ofs.keys.map { |k| [k.humanize, k] }, {}, { class: 'form-control' } %>
    </div>
  </div>

  <div class="form-row">
    <div class="form-group col-md-6">
      <%= form.label :password %>
      <%= form.password_field :password, class: 'form-control' %>
    </div>
    <div class="form-group col-md-6">
      <%= form.label :password_confirmation %>
      <%= form.password_field :password_confirmation, class: 'form-control' %>
    </div>
  </div>

  <div class="actions mt-3">
    <div class="btn-group" role="group" aria-label="Ações">
      <%= form.submit 'Salvar', class: 'btn btn-sm btn-primary' %>
      <%= link_to 'Voltar para Lista', users_path, class: 'btn btn-sm btn-info' %>
    </div>
  </div>
<% end %>

app/views/users/_users_table.html.erb
<table id="users-datatable" data-source="<%= users_path(format: :json) %>" class="table mt-3 mb-3">
  <thead>
    <tr>
      <th>Nome</th>
      <th>Email</th>
      <th>Tipo</th>
      <th>Ações</th>
    </tr>
  </thead>
  <tbody>
  </tbody>
</table>

<%= link_to 'Criar Usuário', new_user_path, class: 'btn btn-sm btn-info mt-3' %>

app/views/users/administrators.html.erb
<div class="jumbotron">
	<h4 class="mb-3">Lista de Administradores</h4>

	<%= render partial: 'users_table', locals: {control_users: @control_users} %>
</div>

app/views/users/edit.html.erb
<div class="jumbotron">
	<h4 class="mb-3">Alterando Usuário</h4>

	<%= render 'form', control_user: @control_user %>
</div>

app/views/users/index.html.erb
<div class="jumbotron">
	<h4 class="mb-3">Lista de Usuários</h4>

	<%= render partial: 'users_table' %>
</div>

app/views/users/new.html.erb
<div class="jumbotron">
	<h4 class="mb-3">Criar Usuário</h4>

	<%= render 'form' %>
</div>

app/views/users/operators.html.erb
<div class="jumbotron">
	<h4 class="mb-3">Lista de Lojas</h4>

	<%= render partial: 'users_table', locals: {control_users: @control_users} %>
</div>